import { StyleSheet } from 'react-native';

export const colors = {
  background: '#E8F5E9',
  primary: '#1ABC9C',
  accent: '#007BFF',
  dark: '#333',
};

const styles = StyleSheet.create({
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#FFA500' },
  container: { flex: 1, backgroundColor: colors.background, paddingTop: 20 },
  header: { fontSize: 26, fontWeight: '800', color: colors.primary, textAlign: 'center', marginBottom: 20, paddingHorizontal: 20, textShadowColor: '#000', textShadowOffset: { width: 1, height: 1 }, textShadowRadius: 3 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 16, marginHorizontal: 15, marginBottom: 15, padding: 16, elevation: 5, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 8 },
  title: { fontSize: 18, fontWeight: '700', color: '#333', marginBottom: 8 },
  subtitle: { fontSize: 16, fontWeight: '600', color: colors.primary, marginBottom: 10 },
  priceText: { fontSize: 24, fontWeight: '900', color: colors.accent, marginTop: 8 },
  backButton: { backgroundColor: '#6C757D' },
  buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  input: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 14, marginBottom: 15, fontSize: 15, borderWidth: 2, borderColor: '#E0E0E0', fontWeight: '500' },
  label: { fontSize: 15, color: '#444', marginBottom: 8, fontWeight: '600' },
  paymentOptionContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 15 },
  paymentOption: { width: '48%', padding: 12, borderRadius: 12, borderWidth: 2, borderColor: '#DDD', alignItems: 'center', marginBottom: 12, backgroundColor: '#F9F9F9' },
  paymentSelected: { borderColor: colors.primary, backgroundColor: '#E5F8F3', borderWidth: 3 },
  paymentText: { fontSize: 14, fontWeight: '700', color: '#333' },
  userTitle: { fontSize: 20, fontWeight: '800', color: '#333', marginBottom: 8 },
  userDescription: { fontSize: 14, color: '#666', textAlign: 'center', marginBottom: 12 },
  registerLink: { alignItems: 'center', marginTop: 20 },
  registerLinkText: { color: colors.accent, fontSize: 15, fontWeight: '700' },
  loginContainer: { flex: 1, justifyContent: 'center', padding: 20 },
  cartBadge: { position: 'absolute', top: 15, right: 20, backgroundColor: colors.primary, borderRadius: 50, width: 32, height: 32, justifyContent: 'center', alignItems: 'center', elevation: 3 },
  cartBadgeText: { color: '#FFF', fontWeight: '900', fontSize: 14 },
  cartItem: { backgroundColor: '#F0F0F0', borderRadius: 12, padding: 12, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderLeftWidth: 4, borderLeftColor: colors.primary },
  cartItemName: { fontSize: 14, fontWeight: '700', color: '#333', flex: 1 },
  cartItemPrice: { fontSize: 14, fontWeight: '800', color: colors.accent, marginHorizontal: 10 },
  quantityControl: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 8, borderWidth: 1, borderColor: '#DDD' },
  quantityButton: { width: 32, height: 32, justifyContent: 'center', alignItems: 'center', fontWeight: '900' },
  quantityText: { fontSize: 13, fontWeight: '800', marginHorizontal: 10, color: '#333' },
  cartTotal: { fontSize: 20, fontWeight: '900', color: colors.primary, marginTop: 15, paddingTop: 15, borderTopWidth: 2, borderTopColor: '#DDD', textAlign: 'right' },
  emptyCart: { textAlign: 'center', fontSize: 16, color: '#999', marginVertical: 20, fontStyle: 'italic' },
  deleteButton: { backgroundColor: '#FF6B6B', padding: 6, borderRadius: 6, marginLeft: 8 },
  deleteButtonText: { color: '#FFF', fontWeight: '700', fontSize: 12 },
  pixModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  pixModalContent: { width: 260, backgroundColor: '#FFFFFF', padding: 20, borderRadius: 16, alignItems: 'center', elevation: 8 },
  qrPlaceholder: { width: 140, height: 140, borderRadius: 12, borderWidth: 2, borderColor: '#28A745', marginVertical: 12, justifyContent: 'center', alignItems: 'center' },
  pixKeyText: { fontSize: 12, textAlign: 'center', color: '#333', marginBottom: 12, fontWeight: '600' },
  orderCard: { borderWidth: 1, borderColor: '#E0E0E0', borderRadius: 14, padding: 16, marginBottom: 12 },
  orderHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  tag: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, backgroundColor: '#FFE6E6', color: colors.primary, fontWeight: '700', fontSize: 12 },
  miniProduct: { width: 40, height: 40, borderRadius: 8, marginRight: 12, backgroundColor: '#FFF' },
  productRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  orderActions: { flexDirection: 'row', justifyContent: 'flex-end' },
  actionButton: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10 },
  actionButtonText: { color: '#FFF', fontWeight: '700' },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#333', marginBottom: 10 },
});

export default styles;
