import { StyleSheet } from 'react-native';

export const themes = {
  light: {
    mode: 'light',
    background: '#F5F7FA',
    card: '#FFFFFF',
    surfaceMuted: '#F0F4F8',
    primary: '#1ABC9C',
    secondary: '#6C757D',
    accent: '#007BFF',
    text: '#1F2933',
    mutedText: '#616E7C',
    border: '#D7DEE7',
    badgeBackground: '#FFE6E6',
    danger: '#FF6B6B',
    success: '#28A745',
    overlay: 'rgba(0,0,0,0.6)',
    highlight: '#E5F8F3',
    shadow: 'rgba(0,0,0,0.12)',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onAccent: '#FFFFFF',
    inputBackground: '#FFFFFF',
    inputBorder: '#E0E6ED',
    statusBar: 'dark-content',
  },
  dark: {
    mode: 'dark',
    background: '#05080F',
    card: '#111827',
    surfaceMuted: '#1F2937',
    primary: '#10B981',
    secondary: '#4B5563',
    accent: '#38BDF8',
    text: '#F5F7FF',
    mutedText: '#B8C5D6',
    border: '#283548',
    badgeBackground: '#1E293B',
    danger: '#FB7185',
    success: '#34D399',
    overlay: 'rgba(0,0,0,0.85)',
    highlight: '#064E3B',
    shadow: 'rgba(0,0,0,0.6)',
    onPrimary: '#04130E',
    onSecondary: '#E2E8F0',
    onAccent: '#04121C',
    inputBackground: '#0F172A',
    inputBorder: '#1F2937',
    statusBar: 'light-content',
  },
};

export const createStyles = (mode = 'light') => {
  const palette = themes[mode] || themes.light;

  return StyleSheet.create({
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: palette.card,
    },
    container: {
      flex: 1,
      backgroundColor: palette.background,
      paddingTop: 20,
    },
    screenContent: {
      paddingBottom: 40,
    },
    header: {
      fontSize: 26,
      fontWeight: '800',
      color: palette.primary,
      textAlign: 'center',
      marginBottom: 20,
      paddingHorizontal: 20,
      textShadowColor: palette.mode === 'dark' ? '#000' : '#2C2C2C',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 3,
    },
    card: {
      backgroundColor: palette.card,
      borderRadius: 16,
      marginHorizontal: 15,
      marginBottom: 15,
      padding: 16,
      elevation: 5,
      shadowColor: palette.shadow,
      shadowOpacity: palette.mode === 'dark' ? 0.45 : 0.12,
      shadowRadius: 8,
    },
    title: {
      fontSize: 18,
      fontWeight: '700',
      color: palette.text,
      marginBottom: 8,
    },
    subtitle: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.primary,
      marginBottom: 10,
    },
    priceText: {
      fontSize: 24,
      fontWeight: '900',
      color: palette.accent,
      marginTop: 8,
    },
    backButton: { backgroundColor: palette.secondary },
    buttonText: { color: palette.onPrimary, fontSize: 16, fontWeight: '800' },
    input: {
      backgroundColor: palette.inputBackground,
      borderRadius: 12,
      padding: 14,
      marginBottom: 15,
      fontSize: 15,
      borderWidth: 2,
      borderColor: palette.inputBorder,
      fontWeight: '500',
      color: palette.text,
    },
    label: {
      fontSize: 15,
      color: palette.text,
      marginBottom: 8,
      fontWeight: '600',
    },
    paymentOptionContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginBottom: 15,
    },
    paymentOption: {
      width: '48%',
      padding: 12,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: palette.border,
      alignItems: 'center',
      marginBottom: 12,
      backgroundColor: palette.surfaceMuted,
    },
    paymentSelected: {
      borderColor: palette.primary,
      backgroundColor: palette.highlight,
      borderWidth: 3,
    },
    paymentText: { fontSize: 14, fontWeight: '700', color: palette.text },
    userTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: palette.text,
      marginBottom: 8,
    },
    userDescription: {
      fontSize: 14,
      color: palette.mutedText,
      textAlign: 'center',
      marginBottom: 12,
    },
    registerLink: { alignItems: 'center', marginTop: 20 },
    registerLinkText: {
      color: palette.accent,
      fontSize: 15,
      fontWeight: '700',
    },
    loginContainer: { flex: 1, justifyContent: 'center', padding: 20 },
    cartBadge: {
      position: 'absolute',
      top: 15,
      right: 20,
      backgroundColor: palette.primary,
      borderRadius: 50,
      width: 32,
      height: 32,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 3,
    },
    cartBadgeText: { color: palette.onPrimary, fontWeight: '900', fontSize: 14 },
    cartItem: {
      backgroundColor: palette.surfaceMuted,
      borderRadius: 12,
      padding: 12,
      marginBottom: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderLeftWidth: 4,
      borderLeftColor: palette.primary,
    },
    cartItemName: {
      fontSize: 14,
      fontWeight: '700',
      color: palette.text,
      flex: 1,
    },
    cartItemPrice: {
      fontSize: 14,
      fontWeight: '800',
      color: palette.accent,
      marginHorizontal: 10,
    },
    quantityControl: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.card,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    quantityButton: {
      width: 32,
      height: 32,
      justifyContent: 'center',
      alignItems: 'center',
      fontWeight: '900',
    },
    quantityText: {
      fontSize: 13,
      fontWeight: '800',
      marginHorizontal: 10,
      color: palette.text,
    },
    cartTotal: {
      fontSize: 20,
      fontWeight: '900',
      color: palette.primary,
      marginTop: 15,
      paddingTop: 15,
      borderTopWidth: 2,
      borderTopColor: palette.border,
      textAlign: 'right',
    },
    emptyCart: {
      textAlign: 'center',
      fontSize: 16,
      color: palette.mutedText,
      marginVertical: 20,
      fontStyle: 'italic',
    },
    deleteButton: {
      backgroundColor: palette.danger,
      padding: 6,
      borderRadius: 6,
      marginLeft: 8,
    },
    deleteButtonText: { color: palette.onPrimary, fontWeight: '700', fontSize: 12 },
    pixModalOverlay: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pixModalContent: {
      width: 260,
      backgroundColor: palette.card,
      padding: 20,
      borderRadius: 16,
      alignItems: 'center',
      elevation: 8,
    },
    qrPlaceholder: {
      width: 140,
      height: 140,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: palette.success,
      marginVertical: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pixKeyText: {
      fontSize: 12,
      textAlign: 'center',
      color: palette.text,
      marginBottom: 12,
      fontWeight: '600',
    },
    orderCard: {
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: 14,
      padding: 16,
      marginBottom: 12,
      backgroundColor: palette.card,
    },
    orderHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    tag: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: palette.badgeBackground,
      color: palette.primary,
      fontWeight: '700',
      fontSize: 12,
    },
    miniProduct: {
      width: 40,
      height: 40,
      borderRadius: 8,
      marginRight: 12,
      backgroundColor: palette.surfaceMuted,
    },
    productRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    orderActions: { flexDirection: 'row', justifyContent: 'flex-end' },
    actionButton: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: palette.primary,
    },
    actionButtonText: { color: palette.onPrimary, fontWeight: '700' },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: palette.text,
      marginBottom: 10,
    },
    themeToggle: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginHorizontal: 15,
      marginBottom: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: palette.card,
      borderWidth: 1,
      borderColor: palette.border,
    },
    themeToggleText: {
      fontWeight: '600',
      fontSize: 15,
      color: palette.text,
    },
    themeToggleHint: {
      fontSize: 12,
      color: palette.mutedText,
      marginTop: 4,
    },
  });
};

const styles = createStyles('light');

export default styles;
